name: Trigger MFramework Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to MFramework
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"ref":"main"}' \
          https://api.github.com/repos/HienNguyen482412/MFramework/actions/workflows/mcm-run-test.yml/dispatches
